project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning Blog"
  navbar:
    background: "#112a39"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ndang01
      - icon: linkedin
        href: www.linkedin.com/in/nhi-dang-6950251b6

format:
  html:
    title-block-banner: img/landscape.png
    title-block-banner-color: white
    theme: cosmo
    css: styles.css





